#!/usr/bin/env perl

use strict;
use warnings;
use File::ShareDir qw();

my ($jar, $epub);

if (scalar @ARGV == 1)
{
    my $epubcheck = "epubcheck-3.0.1/epubcheck.3.0.1.jar";
    $jar  = File::ShareDir::module_file("EBook::EPUB::Valid", $epubcheck);
    $epub = $ARGV[0];
}
elsif (scalar @ARGV == 2)
{
    ($jar, $epub) = @ARGV;
}
else
{
    print "Usage: epubcheck [epubcheck-x.x.x.jar] file.epub\n";
    exit(1);
}

if ( ! -e $jar  ) { print "jar file not found\n";  exit(1); }
if ( ! -e $epub ) { print "epub file not found\n"; exit(1); }

system("java $jar $epub");
